{
 "title": "FreeNAS",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "CPU",
   "type": "graph",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "servers_freenas_local_aggregation_cpu_average_percent_system",
     "legendFormat": "System"
    },
    {
     "expr": "servers_freenas_local_aggregation_cpu_average_percent_interrupt",
     "legendFormat": "Interrupt"
    },
    {
     "expr": "servers_freenas_local_aggregation_cpu_average_percent_user",
     "legendFormat": "User"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "servers_freenas_local_memory_memory_active",
     "legendFormat": "Active"
    },
    {
     "expr": "servers_freenas_local_memory_memory_cache",
     "legendFormat": "Cache"
    },
    {
     "expr": "servers_freenas_local_zfs_arc_cache_size_arc",
     "legendFormat": "ARC"
    },
    {
     "expr": "servers_freenas_local_zfs_arc_cache_size_L2",
     "legendFormat": "L2"
    },
    {
     "expr": "servers_freenas_local_memory_in"
    }
   ]
  },
  {
   "title": "Network (ix0)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "KBs" }
   ],
   "targets": [
    {
     "expr": "servers_freenas_local_interface_ix0_if_packets_rx",
     "legendFormat": "Recieved"
    },
    {
     "expr": "servers_freenas_local_interface_ix0_if_packets_tx",
     "legendFormat": "Sent"
    }
   ]
  },
  {
   "title": "Disk Latency",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 4 },
   "yaxes": [
    { "format": "dtdurationms" }
   ],
   "targets": [
    {
     "expr": "servers_freenas_local_geom_stat_geom_latency_ada0_read",
     "legendFormat": "ada0_read"
    },
    {
     "expr": "servers_freenas_local_geom_stat_geom_latency_ada1_read",
     "legendFormat": "ada1_read"
    },
    {
     "expr": "servers_freenas_local_geom_stat_geom_latency_ada2_read",
     "legendFormat": "ada2_read"
    },
    {
     "expr": "servers_freenas_local_geom_stat_geom_latency_ada3_read",
     "legendFormat": "ada3_read"
    },
    {
     "expr": "servers_freenas_local_geom_stat_geom_latency_ada4_read",
     "legendFormat": "ada4_read"
    },
    {
     "expr": "servers_freenas_local_geom_stat_geom_latency_ada5_read",
     "legendFormat": "ada5_read"
    },
    {
     "expr": "servers_freenas_local_geom_stat_geom_latency_ada0_write",
     "legendFormat": "ada0_write"
    },
    {
     "expr": "servers_freenas_local_geom_stat_geom_latency_ada1_write",
     "legendFormat": "ada1_write"
    },
    {
     "expr": "servers_freenas_local_geom_stat_geom_latency_ada2_write",
     "legendFormat": "ada2_write"
    },
    {
     "expr": "servers_freenas_local_geom_stat_geom_latency_ada3_write",
     "legendFormat": "ada3_write"
    },
    {
     "expr": "servers_freenas_local_geom_stat_geom_latency_ada4_write",
     "legendFormat": "ada4_write"
    },
    {
     "expr": "servers_freenas_local_geom_stat_geom_latency_ada5_write",
     "legendFormat": "ada5_write"
    },
    {
     "expr": "servers_freenas_local_geom_stat_geom_latency_ada0_delete",
     "legendFormat": "ada0_delete"
    },
    {
     "expr": "servers_freenas_local_geom_stat_geom_latency_ada1_delete",
     "legendFormat": "ada1_delete"
    },
    {
     "expr": "servers_freenas_local_geom_stat_geom_latency_ada2_delete",
     "legendFormat": "ada2_delete"
    },
    {
     "expr": "servers_freenas_local_geom_stat_geom_latency_ada3_delete",
     "legendFormat": "ada3_delete"
    },
    {
     "expr": "servers_freenas_local_geom_stat_geom_latency_ada4_delete",
     "legendFormat": "ada4_delete"
    },
    {
     "expr": "servers_freenas_local_geom_stat_geom_latency_ada5_delete",
     "legendFormat": "ada5_delete"
    }
   ]
  },
  {
   "title": "Disk IO",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 4 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "servers_freenas_local_disk_ada0_disk_octets_read",
     "legendFormat": "ada0_read"
    },
    {
     "expr": "servers_freenas_local_disk_ada1_disk_octets_read",
     "legendFormat": "ada1_read"
    },
    {
     "expr": "servers_freenas_local_disk_ada2_disk_octets_read",
     "legendFormat": "ada2_read"
    },
    {
     "expr": "servers_freenas_local_disk_ada3_disk_octets_read",
     "legendFormat": "ada3_read"
    },
    {
     "expr": "servers_freenas_local_disk_ada4_disk_octets_read",
     "legendFormat": "ada4_read"
    },
    {
     "expr": "servers_freenas_local_disk_ada5_disk_octets_read",
     "legendFormat": "ada5_read"
    },
    {
     "expr": "servers_freenas_local_disk_ada0_disk_octets_write",
     "legendFormat": "ada0_write"
    },
    {
     "expr": "servers_freenas_local_disk_ada1_disk_octets_write",
     "legendFormat": "ada1_write"
    },
    {
     "expr": "servers_freenas_local_disk_ada2_disk_octets_write",
     "legendFormat": "ada2_write"
    },
    {
     "expr": "servers_freenas_local_disk_ada3_disk_octets_write",
     "legendFormat": "ada3_write"
    },
    {
     "expr": "servers_freenas_local_disk_ada4_disk_octets_write",
     "legendFormat": "ada4_write"
    },
    {
     "expr": "servers_freenas_local_disk_ada5_disk_octets_write",
     "legendFormat": "ada5_write"
    }
   ]
  },
  {
   "title": "ARC Hit Ratio",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "servers_freenas_local_zfs_arc_v2_arcstat_ratio_arc_hits",
     "legendFormat": "Ratio"
    }
   ]
  },
  {
   "title": "ARC Requests (demand_data)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "servers_freenas_local_zfs_arc_v2_gauge_arcstats_raw_demand_demand_data_hits",
     "legendFormat": "Hit"
    },
    {
     "expr": "servers_freenas_local_zfs_arc_v2_gauge_arcstats_raw_demand_demand_data_misses",
     "legendFormat": "Miss"
    }
   ]
  },
  {
   "title": "ARC Requests (prefetch_data)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "servers_freenas_local_zfs_arc_v2_gauge_arcstats_raw_prefetch_prefetch_data_hits",
     "legendFormat": "Hit"
    },
    {
     "expr": "servers_freenas_local_zfs_arc_v2_gauge_arcstats_raw_prefetch_prefetch_data_misses",
     "legendFormat": "Miss"
    }
   ]
  },
  {
   "title": "CPU Temps",
   "type": "graph",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "expr": "(servers_freenas_local_cputemp_0_temperature - 2731.5)/10",
     "legendFormat": "cputemp_0"
    },
    {
     "expr": "(servers_freenas_local_cputemp_1_temperature - 2731.5)/10",
     "legendFormat": "cputemp_1"
    },
    {
     "expr": "(servers_freenas_local_cputemp_2_temperature - 2731.5)/10",
     "legendFormat": "cputemp_2"
    },
    {
     "expr": "(servers_freenas_local_cputemp_3_temperature - 2731.5)/10",
     "legendFormat": "cputemp_3"
    },
    {
     "expr": "(servers_freenas_local_cputemp_4_temperature - 2731.5)/10",
     "legendFormat": "cputemp_4"
    },
    {
     "expr": "(servers_freenas_local_cputemp_5_temperature - 2731.5)/10",
     "legendFormat": "cputemp_5"
    },
    {
     "expr": "(servers_freenas_local_cputemp_6_temperature - 2731.5)/10",
     "legendFormat": "cputemp_6"
    },
    {
     "expr": "(servers_freenas_local_cputemp_7_temperature - 2731.5)/10",
     "legendFormat": "cputemp_7"
    }
   ]
  },
  {
   "title": "Drive Temperatures",
   "type": "graph",
   "gridPos": { "h": 5, "w": 7, "x": 5, "y": 14 },
   "yaxes": [
    { "format": "degree" }
   ],
   "targets": [
    {
     "expr": "servers_freenas_local_disktemp_ada0_temperature",
     "legendFormat": "ada0"
    },
    {
     "expr": "servers_freenas_local_disktemp_ada1_temperature",
     "legendFormat": "ada1"
    },
    {
     "expr": "servers_freenas_local_disktemp_ada2_temperature",
     "legendFormat": "ada2"
    },
    {
     "expr": "servers_freenas_local_disktemp_ada3_temperature",
     "legendFormat": "ada3"
    },
    {
     "expr": "servers_freenas_local_disktemp_ada4_temperature",
     "legendFormat": "ada4"
    },
    {
     "expr": "servers_freenas_local_disktemp_ada5_temperature",
     "legendFormat": "ada5"
    }
   ]
  },
  {
   "title": "nas-share",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "bits" } },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "servers_freenas_local_df_mnt_pool_1_nas_share_df_complex_free",
     "legendFormat": "Free"
    },
    {
     "expr": "servers_freenas_local_df_mnt_pool_1_nas_share_df_complex_used",
     "legendFormat": "Used"
    }
   ]
  },
  {
   "title": "time-machine",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "bits" } },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "servers_freenas_local_df_mnt_pool_1_time_machine_df_complex_free",
     "legendFormat": "Free"
    },
    {
     "expr": "servers_freenas_local_df_mnt_pool_1_time_machine_df_complex_used",
     "legendFormat": "Used"
    }
   ]
  }
 ]
}