{
 "title": "Master Dashboard",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "type": "stat",
   "description": "http://freenas.local/ui/dashboard",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "12", "legendFormat": "freenas" }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "servers_freenas_local_uptime_uptime",
     "legendFormat": "uptime"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "(34275598336 - servers_freenas_local_memory_memory_free)/34275598336",
     "legendFormat": "% memory use"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "servers_freenas_local_memory_memory_active + servers_freenas_local_memory_memory_cache + servers_freenas_local_memory_memory_inactive + servers_freenas_local_memory_memory_laundry",
     "legendFormat": "memory"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 10, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "servers_freenas_local_memory_memory_wired",
     "legendFormat": "ARC cache"
    }
   ]
  },
  {
   "type": "stat",
   "description": "http://ivymike.local:19999/#menu_system_submenu_cpu;theme=slate",
   "gridPos": { "h": 2, "w": 4, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "12", "legendFormat": "ivymike" }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "netdata_system_uptime", "legendFormat": "uptime" }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "(16256400-netdata_mem_available)/16256400",
     "legendFormat": "% memory use"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "kbytes" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "16256400-netdata_mem_available", "legendFormat": "memory" }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 22, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "netdata_sensors_temperature/1000",
     "legendFormat": "NVMe {{dimension}}"
    }
   ]
  },
  {
   "title": "Intel(R) Atom(TM) CPU C3758 @ 2.20GHz Temperature",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 2 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "expr": "(servers_freenas_local_cputemp_0_temperature - 2731.5)/10",
     "legendFormat": "cputemp_0"
    },
    {
     "expr": "(servers_freenas_local_cputemp_1_temperature - 2731.5)/10",
     "legendFormat": "cputemp_1"
    },
    {
     "expr": "(servers_freenas_local_cputemp_2_temperature - 2731.5)/10",
     "legendFormat": "cputemp_2"
    },
    {
     "expr": "(servers_freenas_local_cputemp_3_temperature - 2731.5)/10",
     "legendFormat": "cputemp_3"
    },
    {
     "expr": "(servers_freenas_local_cputemp_4_temperature - 2731.5)/10",
     "legendFormat": "cputemp_4"
    },
    {
     "expr": "(servers_freenas_local_cputemp_5_temperature - 2731.5)/10",
     "legendFormat": "cputemp_5"
    },
    {
     "expr": "(servers_freenas_local_cputemp_6_temperature - 2731.5)/10",
     "legendFormat": "cputemp_6"
    },
    {
     "expr": "(servers_freenas_local_cputemp_7_temperature - 2731.5)/10",
     "legendFormat": "cputemp_7"
    }
   ]
  },
  {
   "title": "Disk IO",
   "type": "graph",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 2 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "servers_freenas_local_disk_ada0_disk_octets_read",
     "legendFormat": "ada0_read"
    },
    {
     "expr": "servers_freenas_local_disk_ada1_disk_octets_read",
     "legendFormat": "ada1_read"
    },
    {
     "expr": "servers_freenas_local_disk_ada2_disk_octets_read",
     "legendFormat": "ada2_read"
    },
    {
     "expr": "servers_freenas_local_disk_ada3_disk_octets_read",
     "legendFormat": "ada3_read"
    },
    {
     "expr": "servers_freenas_local_disk_ada4_disk_octets_read",
     "legendFormat": "ada4_read"
    },
    {
     "expr": "servers_freenas_local_disk_ada5_disk_octets_read",
     "legendFormat": "ada5_read"
    },
    {
     "expr": "servers_freenas_local_disk_ada0_disk_octets_write",
     "legendFormat": "ada0_write"
    },
    {
     "expr": "servers_freenas_local_disk_ada1_disk_octets_write",
     "legendFormat": "ada1_write"
    },
    {
     "expr": "servers_freenas_local_disk_ada2_disk_octets_write",
     "legendFormat": "ada2_write"
    },
    {
     "expr": "servers_freenas_local_disk_ada3_disk_octets_write",
     "legendFormat": "ada3_write"
    },
    {
     "expr": "servers_freenas_local_disk_ada4_disk_octets_write",
     "legendFormat": "ada4_write"
    },
    {
     "expr": "servers_freenas_local_disk_ada5_disk_octets_write",
     "legendFormat": "ada5_write"
    }
   ]
  },
  {
   "title": "Intel(R) Core(TM) i5-8259U CPU @ 2.30GHz Temperature",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "expr": "netdata_sensors_temperature/1000",
     "legendFormat": "{{dimension}}"
    }
   ]
  },
  {
   "title": "Disk IO",
   "type": "graph",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 2 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "servers_freenas_local_disk_ada0_disk_octets_read",
     "legendFormat": "ada0_read"
    },
    {
     "expr": "servers_freenas_local_disk_ada1_disk_octets_read",
     "legendFormat": "ada1_read"
    },
    {
     "expr": "servers_freenas_local_disk_ada2_disk_octets_read",
     "legendFormat": "ada2_read"
    },
    {
     "expr": "servers_freenas_local_disk_ada3_disk_octets_read",
     "legendFormat": "ada3_read"
    },
    {
     "expr": "servers_freenas_local_disk_ada4_disk_octets_read",
     "legendFormat": "ada4_read"
    },
    {
     "expr": "servers_freenas_local_disk_ada5_disk_octets_read",
     "legendFormat": "ada5_read"
    },
    {
     "expr": "servers_freenas_local_disk_ada0_disk_octets_write",
     "legendFormat": "ada0_write"
    },
    {
     "expr": "servers_freenas_local_disk_ada1_disk_octets_write",
     "legendFormat": "ada1_write"
    },
    {
     "expr": "servers_freenas_local_disk_ada2_disk_octets_write",
     "legendFormat": "ada2_write"
    },
    {
     "expr": "servers_freenas_local_disk_ada3_disk_octets_write",
     "legendFormat": "ada3_write"
    },
    {
     "expr": "servers_freenas_local_disk_ada4_disk_octets_write",
     "legendFormat": "ada4_write"
    },
    {
     "expr": "servers_freenas_local_disk_ada5_disk_octets_write",
     "legendFormat": "ada5_write"
    }
   ]
  },
  {
   "title": "Network (ix0)",
   "type": "graph",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 6 },
   "yaxes": [
    { "format": "KBs" }
   ],
   "targets": [
    {
     "expr": "servers_freenas_local_interface_ix0_if_packets_rx",
     "legendFormat": "Recieved"
    },
    {
     "expr": "servers_freenas_local_interface_ix0_if_packets_tx",
     "legendFormat": "Sent"
    }
   ]
  },
  {
   "title": "Network (eno1)",
   "type": "graph",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 6 },
   "yaxes": [
    { "format": "KBs" }
   ],
   "targets": [
    { "expr": "net" }
   ]
  },
  {
   "title": "Load Average",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "servers_freenas_local_load_load_shortterm",
     "legendFormat": "1 min"
    },
    {
     "expr": "servers_freenas_local_load_load_midterm",
     "legendFormat": "5 min"
    },
    {
     "expr": "servers_freenas_local_load_load_longterm",
     "legendFormat": "15 min"
    }
   ]
  },
  {
   "title": "Load Average",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "netdata_system_load/1000", "legendFormat": "{{dimension}}" }
   ]
  },
  {
   "title": "Disk Latency",
   "type": "graph",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 10 },
   "yaxes": [
    { "format": "dtdurationms" }
   ],
   "targets": [
    {
     "expr": "servers_freenas_local_geom_stat_geom_latency_ada0_read",
     "legendFormat": "ada0_read"
    },
    {
     "expr": "servers_freenas_local_geom_stat_geom_latency_ada1_read",
     "legendFormat": "ada1_read"
    },
    {
     "expr": "servers_freenas_local_geom_stat_geom_latency_ada2_read",
     "legendFormat": "ada2_read"
    },
    {
     "expr": "servers_freenas_local_geom_stat_geom_latency_ada3_read",
     "legendFormat": "ada3_read"
    },
    {
     "expr": "servers_freenas_local_geom_stat_geom_latency_ada4_read",
     "legendFormat": "ada4_read"
    },
    {
     "expr": "servers_freenas_local_geom_stat_geom_latency_ada5_read",
     "legendFormat": "ada5_read"
    },
    {
     "expr": "servers_freenas_local_geom_stat_geom_latency_ada0_write",
     "legendFormat": "ada0_write"
    },
    {
     "expr": "servers_freenas_local_geom_stat_geom_latency_ada1_write",
     "legendFormat": "ada1_write"
    },
    {
     "expr": "servers_freenas_local_geom_stat_geom_latency_ada2_write",
     "legendFormat": "ada2_write"
    },
    {
     "expr": "servers_freenas_local_geom_stat_geom_latency_ada3_write",
     "legendFormat": "ada3_write"
    },
    {
     "expr": "servers_freenas_local_geom_stat_geom_latency_ada4_write",
     "legendFormat": "ada4_write"
    },
    {
     "expr": "servers_freenas_local_geom_stat_geom_latency_ada5_write",
     "legendFormat": "ada5_write"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 6, "x": 18, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "netdata_docker_running_containers",
     "legendFormat": "Docker - Running"
    },
    {
     "expr": "netdata_docker_healthy_containers",
     "legendFormat": "Healthy"
    },
    {
     "expr": "netdata_docker_unhealthy_containers",
     "legendFormat": "Unhealthy"
    }
   ]
  },
  {
   "title": "Drive Temperatures",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "servers_freenas_local_disktemp_ada0_temperature",
     "legendFormat": "ada0"
    },
    {
     "expr": "servers_freenas_local_disktemp_ada1_temperature",
     "legendFormat": "ada1"
    },
    {
     "expr": "servers_freenas_local_disktemp_ada2_temperature",
     "legendFormat": "ada2"
    },
    {
     "expr": "servers_freenas_local_disktemp_ada3_temperature",
     "legendFormat": "ada3"
    },
    {
     "expr": "servers_freenas_local_disktemp_ada4_temperature",
     "legendFormat": "ada4"
    },
    {
     "expr": "servers_freenas_local_disktemp_ada5_temperature",
     "legendFormat": "ada5"
    },
    {
     "expr": "servers_freenas_local_disktemp_nvd0_temperature",
     "legendFormat": "nvd0"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 12 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    { "expr": "netdata_apps_cpu/10000", "legendFormat": "{{dimension}}" }
   ]
  },
  {
   "title": "ARC Hits + Misses",
   "type": "graph",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "servers_freenas_local_zfs_arc_v2_gauge_arcstats_raw_demand_demand_data_hits",
     "legendFormat": "data hit"
    },
    {
     "expr": "servers_freenas_local_zfs_arc_v2_gauge_arcstats_raw_demand_demand_data_misses",
     "legendFormat": "data miss"
    },
    {
     "expr": "servers_freenas_local_zfs_arc_v2_gauge_arcstats_raw_demand_demand_metadata_hits",
     "legendFormat": "metadata hit"
    },
    {
     "expr": "servers_freenas_local_zfs_arc_v2_gauge_arcstats_raw_prefetch_prefetch_data_hits",
     "legendFormat": "metadata miss"
    }
   ]
  },
  {
   "title": "Pool 1 (Mirrored ZFS)",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 17 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "servers_freenas_local_df_mnt_pool_1_time_machine_df_complex_free + servers_freenas_local_df_mnt_pool_1_nas_share_df_complex_free",
     "legendFormat": "Free"
    },
    {
     "expr": "servers_freenas_local_df_mnt_pool_1_nas_share_df_complex_used",
     "legendFormat": "NAS Share"
    },
    {
     "expr": "servers_freenas_local_df_mnt_pool_1_time_machine_df_complex_used",
     "legendFormat": "Time Machine"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "netdata_apps_mem", "legendFormat": "{{dimension}}" }
   ]
  },
  {
   "title": "ARC Hit Ratio",
   "type": "graph",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 18 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "servers_freenas_local_zfs_arc_v2_arcstat_ratio_arc_hits",
     "legendFormat": "Ratio"
    }
   ]
  }
 ]
}