{
 "title": "Master Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "Intel(R) Core(TM) i5-8259U CPU @ 2.30GHz",
   "type": "graph",
   "gridPos": { "h": 5, "w": 13, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    { "legendFormat": "cputemp_0" },
    {
     "expr": "(servers_freenas_local_cputemp_1_temperature - 2731.5)/10",
     "legendFormat": "cputemp_1"
    },
    {
     "expr": "(servers_freenas_local_cputemp_2_temperature - 2731.5)/10",
     "legendFormat": "cputemp_2"
    },
    {
     "expr": "(servers_freenas_local_cputemp_3_temperature - 2731.5)/10",
     "legendFormat": "cputemp_3"
    },
    {
     "expr": "(servers_freenas_local_cputemp_4_temperature - 2731.5)/10",
     "legendFormat": "cputemp_4"
    },
    {
     "expr": "(servers_freenas_local_cputemp_5_temperature - 2731.5)/10",
     "legendFormat": "cputemp_5"
    },
    {
     "expr": "(servers_freenas_local_cputemp_6_temperature - 2731.5)/10",
     "legendFormat": "cputemp_6"
    },
    {
     "expr": "(servers_freenas_local_cputemp_7_temperature - 2731.5)/10",
     "legendFormat": "cputemp_7"
    }
   ]
  },
  {
   "title": "FreeNAS",
   "type": "stat",
   "gridPos": { "h": 3, "w": 15, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "servers_freenas_local_uptime_uptime",
     "legendFormat": "Uptime"
    },
    { "expr": "12", "legendFormat": "Random Value LOL" }
   ]
  },
  {
   "title": "Intel(R) Atom(TM) CPU C3758 @ 2.20GHz",
   "type": "graph",
   "gridPos": { "h": 5, "w": 13, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "expr": "(servers_freenas_local_cputemp_0_temperature - 2731.5)/10",
     "legendFormat": "cputemp_0"
    },
    {
     "expr": "(servers_freenas_local_cputemp_1_temperature - 2731.5)/10",
     "legendFormat": "cputemp_1"
    },
    {
     "expr": "(servers_freenas_local_cputemp_2_temperature - 2731.5)/10",
     "legendFormat": "cputemp_2"
    },
    {
     "expr": "(servers_freenas_local_cputemp_3_temperature - 2731.5)/10",
     "legendFormat": "cputemp_3"
    },
    {
     "expr": "(servers_freenas_local_cputemp_4_temperature - 2731.5)/10",
     "legendFormat": "cputemp_4"
    },
    {
     "expr": "(servers_freenas_local_cputemp_5_temperature - 2731.5)/10",
     "legendFormat": "cputemp_5"
    },
    {
     "expr": "(servers_freenas_local_cputemp_6_temperature - 2731.5)/10",
     "legendFormat": "cputemp_6"
    },
    {
     "expr": "(servers_freenas_local_cputemp_7_temperature - 2731.5)/10",
     "legendFormat": "cputemp_7"
    }
   ]
  },
  {
   "title": "Load Average",
   "type": "graph",
   "gridPos": { "h": 5, "w": 11, "x": 13, "y": 8 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "servers_freenas_local_load_load_shortterm",
     "legendFormat": "1 min"
    },
    {
     "expr": "servers_freenas_local_load_load_midterm",
     "legendFormat": "5 min"
    },
    {
     "expr": "servers_freenas_local_load_load_longterm",
     "legendFormat": "15 min"
    }
   ]
  },
  {
   "title": "Pool 1 (Mirrored ZFS)",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 5, "w": 9, "x": 0, "y": 13 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "servers_freenas_local_df_mnt_pool_1_time_machine_df_complex_free + servers_freenas_local_df_mnt_pool_1_nas_share_df_complex_free",
     "legendFormat": "Free"
    },
    {
     "expr": "servers_freenas_local_df_mnt_pool_1_nas_share_df_complex_used",
     "legendFormat": "NAS Share"
    },
    {
     "expr": "servers_freenas_local_df_mnt_pool_1_time_machine_df_complex_used",
     "legendFormat": "Time Machine"
    }
   ]
  },
  {
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 7, "x": 9, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "servers_freenas_local_disktemp_ada0_temperature",
     "legendFormat": "ada0"
    },
    {
     "expr": "servers_freenas_local_disktemp_ada1_temperature",
     "legendFormat": "ada1"
    },
    {
     "expr": "servers_freenas_local_disktemp_ada2_temperature",
     "legendFormat": "ada2"
    },
    {
     "expr": "servers_freenas_local_disktemp_ada3_temperature",
     "legendFormat": "ada3"
    },
    {
     "expr": "servers_freenas_local_disktemp_ada4_temperature",
     "legendFormat": "ada4"
    },
    {
     "expr": "servers_freenas_local_disktemp_ada5_temperature",
     "legendFormat": "ada5"
    }
   ]
  },
  {
   "title": "Network (ix0)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "KBs" }
   ],
   "targets": [
    {
     "expr": "servers_freenas_local_interface_ix0_if_packets_rx",
     "legendFormat": "Recieved"
    },
    {
     "expr": "servers_freenas_local_interface_ix0_if_packets_tx",
     "legendFormat": "Sent"
    }
   ]
  },
  {
   "title": "ARC Hits+Misses",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 8, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "servers_freenas_local_zfs_arc_v2_gauge_arcstats_raw_demand_demand_data_hits",
     "legendFormat": "data hit"
    },
    {
     "expr": "servers_freenas_local_zfs_arc_v2_gauge_arcstats_raw_demand_demand_data_misses",
     "legendFormat": "data miss"
    },
    {
     "expr": "servers_freenas_local_zfs_arc_v2_gauge_arcstats_raw_demand_demand_metadata_hits",
     "legendFormat": "metadata hit"
    },
    {
     "expr": "servers_freenas_local_zfs_arc_v2_gauge_arcstats_raw_prefetch_prefetch_data_hits",
     "legendFormat": "metadata miss"
    }
   ]
  },
  {
   "title": "ARC Requests (prefetch_data)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 15, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "servers_freenas_local_zfs_arc_v2_gauge_arcstats_raw_prefetch_prefetch_data_hits",
     "legendFormat": "Hit"
    },
    {
     "expr": "servers_freenas_local_zfs_arc_v2_gauge_arcstats_raw_prefetch_prefetch_data_misses",
     "legendFormat": "Miss"
    }
   ]
  }
 ]
}